---
sudo: required
services:
  - docker

language: ruby
rvm:
  - 2.4
cache: bundler

env:
  - TEST_FILE: ubuntu_bionic_spec.rb
  - TEST_FILE: ubuntu_xenial_spec.rb
  - TEST_FILE: ubuntu_trusty_spec.rb
  - TEST_FILE: centos7_spec.rb
  - TEST_FILE: debian_jessie_spec.rb
  - TEST_FILE: debian_stretch_spec.rb

before_install:
  - nvm install 8.3.0
  - npm install

script:
  - npm test
  - bundle exec rspec spec/${TEST_FILE}

after_success:
  - docker images

notifications:
  email: false