---
sudo: required
services:
  - docker

language: ruby
rvm:
  - 2.4
cache: bundler

env:
  - SUITE: ubuntu18.04
  - SUITE: ubuntu16.04
  - SUITE: ubuntu14.04
  - SUITE: centos7
  - SUITE: debian8
  - SUITE: debian9

before_install:
  - docker pull hadolint/hadolint

script:
  - docker run -i hadolint/hadolint hadolint --ignore DL3008 - < "${SUITE}"/Dockerfile
  - bundle exec rspec spec/"${SUITE}"_spec.rb

after_success:
  - docker images

notifications:
  email: false